### ISSUE TITLE
Multiorbital problem

### ISSUE THREAD

**Issue by SamueleGiuli** [QcmPlab/LIB_DMFT_ED#1]
ED_OBSERVABLES_SUPERC.f90 at line 169 sectorI is deleted before spanning all orbitals, should be brought outside of for cycle

**Comment by aamaricci** [comment]
I see. 
Good point. 

The `delete_sector(sectorI)` @line 169 should definitively go at line 173, outside the two do loops on spin and orbitals. 
Yet before the endif as only the master evaluates the order parameter. 

If you want to fix it, you can push after wards. 
Thanks.

A

**Comment by SamueleGiuli** [comment]
Solved
