### ISSUE TITLE
Real-space DMFT Neigen initialization

### ISSUE THREAD

**Issue by lcrippa** [QcmPlab/LIB_DMFT_ED#2]
in `ED_MAIN.f90`, in subroutine `ed_solve_lattice_mpi` the following is issued:

`neigen_sector_ineq=0 ; neigen_total_ineq =0`

this overrides the previous initialization and sets the number of required eigenvectors for every sector to 0 (of course then arpack fails). Could probably be fixed just by removing this line. I can do it if you agree

**Comment by aamaricci** [comment]
I removed the suspected line. 
Indeed neigen_sector_ineq AND neigen_total_ineq are initialised at the init step (either default or read from file). 
These arrays are then used to retrieve site by site the correct number of eigensolutions to get per sector and in total. 
These values are then modified inside ed_solve (if T>0). The two cases follow:
1) if sites are treated in parallel (mpi_lanc=False) then neigen_sector; neigen_total are saved into tmp arrays and reduced at the end of the cycle across the sites. Note that reduction indeed required to set neigen_sector_ineq=0 ; neigen_total_ineq =0. 
2) each site is solved using parallel lanczos, one after the other. The corresponding solution are dumped into the _ineq arrays site by site. No reduction is required so the bugged line is of no use now.
