### ISSUE TITLE
Possible error in analytic gradient for `bath_type='general'`

### ISSUE THREAD

**Issue by bellomia** [QcmPlab/LIB_DMFT_ED#4]
https://github.com/QcmPlab/LIB_DMFT_ED/blob/900859dcd2d33f44dee501bbd5870481ec355e84/src/ED_BATH/ED_FIT_GENERAL.f90#L526-L528

Since `invH_knn` is not initialized upstream in `grad_delta_general`  I believe these are junk lines, perhaps a vestigia of some intermediate rewrite. Check them out please :) 

@SamueleGiuli

**Comment by SamueleGiuli** [comment]
It was a junk line indeed. It has been removed in commit 5540fd9b42b8a0beeb860d633d7ad6f2bc856ced , thank you @bellomia !
